/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary":                    "#00452e",
        "on-primary":                 "#ffffff",
        "primary-container":          "#1f5d43",
        "on-primary-container":       "#95d4b3",
        "primary-fixed":              "#b1f0ce",
        "primary-fixed-dim":          "#95d4b3",
        "on-primary-fixed":           "#002114",
        "on-primary-fixed-variant":   "#0e5138",
        "secondary":                  "#284cdb",
        "on-secondary":               "#ffffff",
        "secondary-container":        "#4767f5",
        "on-secondary-container":     "#fffbff",
        "secondary-fixed":            "#dee1ff",
        "secondary-fixed-dim":        "#b9c3ff",
        "on-secondary-fixed":         "#001258",
        "on-secondary-fixed-variant": "#0033c2",
        "tertiary":                   "#593300",
        "on-tertiary":                "#ffffff",
        "tertiary-container":         "#794700",
        "on-tertiary-container":      "#ffb86c",
        "tertiary-fixed":             "#ffdcbc",
        "tertiary-fixed-dim":         "#ffb86b",
        "on-tertiary-fixed":          "#2c1700",
        "on-tertiary-fixed-variant":  "#683d00",
        "surface":                    "#f8f9fa",
        "surface-dim":                "#d9dadb",
        "surface-bright":             "#f8f9fa",
        "surface-container-lowest":   "#ffffff",
        "surface-container-low":      "#f3f4f5",
        "surface-container":          "#edeeef",
        "surface-container-high":     "#e7e8e9",
        "surface-container-highest":  "#e1e3e4",
        "surface-variant":            "#e1e3e4",
        "on-surface":                 "#191c1d",
        "on-surface-variant":         "#424842",
        "inverse-surface":            "#2e3132",
        "inverse-on-surface":         "#f0f1f2",
        "inverse-primary":            "#95d4b3",
        "surface-tint":               "#2c694e",
        "outline":                    "#727971",
        "outline-variant":            "#c2c8bf",
        "background":                 "#f8f9fa",
        "on-background":              "#191c1d",
        "error":                      "#ba1a1a",
        "on-error":                   "#ffffff",
        "error-container":            "#ffdad6",
        "on-error-container":         "#93000a",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body:     ["Work Sans", "sans-serif"],
        label:    ["Work Sans", "sans-serif"],
      },
      // Design system radius scale — intentionally smaller than Tailwind defaults.
      // Cards use `rounded-xl` (0.5rem), buttons use `rounded-full` (Tailwind default: 9999px = pill shape).
      borderRadius: {
        DEFAULT: "0.125rem",
        sm:      "0.125rem",
        lg:      "0.25rem",
        xl:      "0.5rem",
        // Note: `full` is intentionally NOT overridden — keep Tailwind default 9999px for pill buttons.
      },
    },
  },
  plugins: [],
};
